<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-03-14T18:12:04+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'locale' => 'fr_FR',
    'site' => 'Factorian',
    'version_installed' => '5.7.5.13',
    'misc' => array(
        'access_entity_updated' => 1516196590,
        'latest_version' => '8.2.1',
        'do_page_reindex_check' => false,
    ),
);
